#!/bin/bash

DST_DIR=../riakng/core/riakpb/
protoc --python_out=$DST_DIR riak.proto
protoc --python_out=$DST_DIR riak_kv.proto
protoc --python_out=$DST_DIR riak_search.proto
echo All files compiled if there are no other messages than this.
